server:
  port: 8080

debug: true

spring:

  # application.yml
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

    devtools:
      restart:
        enabled: true
    freemarker:
      cache: false



